version: '2'

services:
    web:
      #restart: always
      build: ./web
      expose:
        - "8000"
      depends_on:
        - postgres
      volumes:
        - ./web:/usr/src/app
        # - ./web/static:/usr/src/app/static
        # - ./web/migrations:/usr/src/app/migrations
      env_file: .env
      # command: /usr/local/bin/gunicorn -w 2 -b :8000 app:app
      # command: /usr/local/bin/gunicorn -w 2 -b :8000 --log-level=DEBUG app:app
      command: /usr/local/bin/gunicorn -w 2 -b :8000 --reload app:app

    nginx:
      #restart: always
      build: ./nginx/
      ports:
        - "80:80"
      volumes:
        - /www/static
      volumes_from:
        - web
      depends_on:
        - web

    postgres:
      #restart: always
      # https://hub.docker.com/_/postgres/
      image: postgres:9.6-alpine
      volumes:
        - db-volume:/var/lib/postgresql

volumes:
    db-volume: {}
