web:
  restart: always
  build: ./web
  expose:
    - "8000"
  links:
    - postgres:postgres
  volumes:
    - /usr/src/app/static
  env_file: .env
  command: /usr/local/bin/gunicorn -w 2 -b :8000 app:app

nginx:
  restart: always
  build: ./nginx/
  ports:
    - "80:80"
  volumes:
    - /www/static
  volumes_from:
    - web
  links:
    - web:web

data:
  # https://hub.docker.com/_/postgres/
  image: postgres:9.6-alpine
  volumes:
    - /var/lib/postgresql
  command: "true"

postgres:
  restart: always
  # https://hub.docker.com/_/postgres/
  image: postgres:9.6-alpine
  volumes_from:
    - data
  ports:
    - "5432:5432"
