"""added target server run metrics url

Revision ID: 0a40b3785b2d
Revises: 4640d5af5d41
Create Date: 2017-04-20 20:29:09.287575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a40b3785b2d'
down_revision = '4640d5af5d41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_result', sa.Column('target_server_run_metrics_url', sa.String(length=1333), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_result', 'target_server_run_metrics_url')
    # ### end Alembic commands ###
