"""empty message

Revision ID: 221e8b598f94
Revises: b6113b96cc90
Create Date: 2017-03-22 09:49:19.438159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '221e8b598f94'
down_revision = 'b6113b96cc90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('server', sa.Column('full_name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('server', 'full_name')
    # ### end Alembic commands ###
