"""empty message

Revision ID: 2a5dfd92245e
Revises: e7e408978779
Create Date: 2017-03-18 15:12:49.924953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a5dfd92245e'
down_revision = 'e7e408978779'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('test_result', 'test_plan_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('test_result', 'test_plan_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
