"""empty message

Revision ID: 5620f6140e71
Revises: e4a4c5beb88d
Create Date: 2017-03-22 16:50:42.957085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5620f6140e71'
down_revision = 'e4a4c5beb88d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_result', sa.Column('test_passed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_result', 'test_passed')
    # ### end Alembic commands ###
