"""add prerun, run, postrun, and failure notes

Revision ID: 5c12ce152d72
Revises: 95ecf01d9cb4
Create Date: 2017-03-30 10:14:05.653235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c12ce152d72'
down_revision = '95ecf01d9cb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_result', sa.Column('failure_notes', sa.Text(), nullable=True))
    op.add_column('test_result', sa.Column('postrun_notes', sa.Text(), nullable=True))
    op.add_column('test_result', sa.Column('prerun_notes', sa.Text(), nullable=True))
    op.add_column('test_result', sa.Column('run_notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_result', 'run_notes')
    op.drop_column('test_result', 'prerun_notes')
    op.drop_column('test_result', 'postrun_notes')
    op.drop_column('test_result', 'failure_notes')
    # ### end Alembic commands ###
