"""make source_server_id not required

Revision ID: 6b98b9039f26
Revises: d0d484c240cf
Create Date: 2017-03-26 18:15:51.055504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b98b9039f26'
down_revision = 'd0d484c240cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('test_result', 'source_server_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('test_result', 'source_server_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
