"""create server_run_metrics structure

Revision ID: 70d7bfcbd8a6
Revises: dd12ac659cc5
Create Date: 2017-04-14 20:41:38.052462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70d7bfcbd8a6'
down_revision = 'dd12ac659cc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('run_metric',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=33), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('server_run_metric',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_metric_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['run_metric_id'], ['run_metric.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('target_serverrunmetric_testresults',
    sa.Column('testresult_id', sa.Integer(), nullable=True),
    sa.Column('server_run_metric_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['server_run_metric_id'], ['server_run_metric.id'], ),
    sa.ForeignKeyConstraint(['testresult_id'], ['test_result.id'], )
    )
    # load run_metric table with initial data.
    op.execute("INSERT INTO run_metric (name,note,creator_id) VALUES ('CPU Min','Minimum CPU',1)")
    op.execute("INSERT INTO run_metric (name,note,creator_id) VALUES ('CPU Max','Maximum CPU',1)")
    op.execute("INSERT INTO run_metric (name,note,creator_id) VALUES ('CPU Avg','Average CPU',1)")
    op.execute("INSERT INTO run_metric (name,note,creator_id) VALUES ('Load Min','Minimum Load',1)")
    op.execute("INSERT INTO run_metric (name,note,creator_id) VALUES ('Load Max','Maximum Load',1)")
    op.execute("INSERT INTO run_metric (name,note,creator_id) VALUES ('Load Avg','Average Load',1)")
    op.execute("INSERT INTO run_metric (name,note,creator_id) VALUES ('Mem Free Min','Minimum Free Memory',1)")
    op.execute("INSERT INTO run_metric (name,note,creator_id) VALUES ('Mem Free Max','Maximum Free Memory',1)")
    op.execute("INSERT INTO run_metric (name,note,creator_id) VALUES ('Mem Free Avg','Average Free Memory',1)")
    op.execute("INSERT INTO run_metric (name,note,creator_id) VALUES ('Mem App Min','Minimum App Memory',1)")
    op.execute("INSERT INTO run_metric (name,note,creator_id) VALUES ('Mem App Max','Maximum App Memory',1)")
    op.execute("INSERT INTO run_metric (name,note,creator_id) VALUES ('Mem App Avg','Average App Memory',1)")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('target_serverrunmetric_testresults')
    op.drop_table('server_run_metric')
    op.drop_table('run_metric')
    # ### end Alembic commands ###
