"""added server.active and server.version

Revision ID: 896d9e43e7a2
Revises: f629a3510fde
Create Date: 2017-03-25 09:30:16.571660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '896d9e43e7a2'
down_revision = 'f629a3510fde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('server', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('server', sa.Column('version', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('server', 'version')
    op.drop_column('server', 'active')
    # ### end Alembic commands ###
