"""empty message

Revision ID: 8cada5e2669b
Revises: e856a21482cd
Create Date: 2017-03-14 22:04:32.080361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cada5e2669b'
down_revision = 'e856a21482cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_plan', sa.Column('creator_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'test_plan', 'user', ['creator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'test_plan', type_='foreignkey')
    op.drop_column('test_plan', 'creator_id')
    # ### end Alembic commands ###
