"""empty message

Revision ID: 915304e6bec7
Revises: d1fa282c5e2a
Create Date: 2017-03-10 22:08:39.185488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '915304e6bec7'
down_revision = 'd1fa282c5e2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('server', 'creator_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('user', sa.Column('name', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('username', sa.String(length=33), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'username')
    op.drop_column('user', 'name')
    op.alter_column('server', 'creator_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
