"""drop single occurring source_server[_id] from model

Revision ID: 93aea2662aa5
Revises: 6b98b9039f26
Create Date: 2017-03-27 21:04:08.461576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93aea2662aa5'
down_revision = '6b98b9039f26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('test_result_source_server_id_fkey', 'test_result', type_='foreignkey')
    op.drop_column('test_result', 'source_server_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_result', sa.Column('source_server_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('test_result_source_server_id_fkey', 'test_result', 'server', ['source_server_id'], ['id'])
    # ### end Alembic commands ###
