"""empty message

Revision ID: b6113b96cc90
Revises: 2a5dfd92245e
Create Date: 2017-03-22 09:17:28.035413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6113b96cc90'
down_revision = '2a5dfd92245e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_plan', sa.Column('dependencies', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_plan', 'dependencies')
    # ### end Alembic commands ###
