"""added active column to TestPlans

Revision ID: bdf99a876c5d
Revises: 81c3bd011b88
Create Date: 2017-08-05 10:47:07.880244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdf99a876c5d'
down_revision = '81c3bd011b88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_plan', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###
    # set all items to active=true
    op.execute("UPDATE test_plan SET active=true")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_plan', 'active')
    # ### end Alembic commands ###
