"""changing source_server_id to use m:m source_servers to allow multiple source (sending) servers

Revision ID: d0d484c240cf
Revises: 896d9e43e7a2
Create Date: 2017-03-26 17:50:42.549434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0d484c240cf'
down_revision = '896d9e43e7a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('server_testresults',
    sa.Column('testresult_id', sa.Integer(), nullable=True),
    sa.Column('server_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['server_id'], ['server.id'], ),
    sa.ForeignKeyConstraint(['testresult_id'], ['test_result.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('server_testresults')
    # ### end Alembic commands ###
