"""remove test_passed column

Revision ID: dd12ac659cc5
Revises: 5c12ce152d72
Create Date: 2017-03-30 10:30:56.408956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd12ac659cc5'
down_revision = '5c12ce152d72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_result', 'test_passed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_result', sa.Column('test_passed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
