"""empty message

Revision ID: e4a4c5beb88d
Revises: 221e8b598f94
Create Date: 2017-03-22 10:10:58.443021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4a4c5beb88d'
down_revision = '221e8b598f94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_result', sa.Column('run_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'test_result', 'user', ['run_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'test_result', type_='foreignkey')
    op.drop_column('test_result', 'run_by_id')
    # ### end Alembic commands ###
