"""cleanup required fields

Revision ID: f629a3510fde
Revises: af4eba0a7b30
Create Date: 2017-03-24 20:08:08.893160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f629a3510fde'
down_revision = 'af4eba0a7b30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('test_result', 'run_by_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('test_result', 'run_by_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
