# @TODO change to alpine per below.
FROM python:3.4-onbuild

# try to get local db (sqlite) - didn't work.
# RUN apt-get update && apt-get install -y --no-install-recommends \
#    sqlite

# https://hub.docker.com/_/python/
#FROM python:3.6-alpine

# NOTE: the following is only needed for develop/debug purposes.
#RUN apk add --no-cache bash sqlite

# copy project files.
#ADD requirements.txt /

# install requirements.
#RUN pip install -r /requirements.txt
